name: npm test
on:
  push:

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: setup checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup cache
        uses: actions/cache@v3.0.2
        env:
          cache-name: cache-node-modules
        with:
          node-version: 'lts/*'
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: run install
        shell: bash
        run: |
          npm install

  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: run test
        shell: bash
        run: |
          npm test